FROM python:3.13-alpine
ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1
ENV ENV production

WORKDIR /repository

RUN pip install --no-cache poetry

COPY . .
RUN poetry install --no-dev

EXPOSE 8000
CMD poetry run gunicorn repository.main:app --bind 0.0.0.0:8000 -k uvicorn.workers.UvicornWorker
