"""New enums

Revision ID: 6b7ef6fc4fd8
Revises: f63774d20171
Create Date: 2024-12-09 18:44:56.684044

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6b7ef6fc4fd8"
down_revision: Union[str, None] = "f63774d20171"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TYPE public.roleenum;")
    op.execute("DROP TYPE public.organizationpermission;")
    op.execute("DROP TYPE public.rolepermission;")
    op.execute(
        "CREATE TYPE permission_new AS ENUM ('ROLE_ACL', 'SUBJECT_NEW', 'SUBJECT_DOWN', 'SUBJECT_UP', 'DOC_NEW', 'ROLE_NEW', 'ROLE_DOWN', 'ROLE_UP', 'ROLE_MOD');"
    )
    op.execute(
        "ALTER TABLE organizationrole ALTER COLUMN permissions TYPE permission_new USING permissions::text::permission_new;"
    )
    op.execute("DROP TYPE public.permission;")
    op.execute("ALTER TYPE permission_new RENAME TO permission;")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
