"""Add session to n:m relation

Revision ID: 82df7500b8bd
Revises: c5aef9a1a909
Create Date: 2024-10-30 19:49:28.648229

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "82df7500b8bd"
down_revision: Union[str, None] = "c5aef9a1a909"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subjectorganizationlink",
        sa.Column("session", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subjectorganizationlink", "session")
    # ### end Alembic commands ###
