"""Set new session column type

Revision ID: 92d2309975cf
Revises: 82df7500b8bd
Create Date: 2024-11-02 19:37:12.341959

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from alembic.ddl import postgresql

from repository.models.nested_base import JSONBPydanticField
from repository.models.session import Session

# revision identifiers, used by Alembic.
revision: str = "92d2309975cf"
down_revision: Union[str, None] = "82df7500b8bd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "subjectorganizationlink",
        "session",
        type_=JSONBPydanticField(pydantic_model_class=Session, astext_type=sa.Text()),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "subjectorganizationlink",
        "session",
        type_=postgresql.JSONB(astext_type=sa.Text()),
        nullable=True,
    )
    # ### end Alembic commands ###
