"""Remove password field from subject

Revision ID: d29028ade0cf
Revises: 773760af9856
Create Date: 2024-10-30 13:02:21.522575

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d29028ade0cf"
down_revision: Union[str, None] = "773760af9856"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "document", "file_handle", existing_type=sa.VARCHAR(), nullable=True
    )
    op.create_index(op.f("ix_document_name"), "document", ["name"], unique=False)
    op.drop_column("subject", "password")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subject",
        sa.Column("password", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_index(op.f("ix_document_name"), table_name="document")
    op.alter_column(
        "document", "file_handle", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
