"""Move subject active status to organization link

Revision ID: f63774d20171
Revises: c959e775735e
Create Date: 2024-12-03 14:19:53.226950

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f63774d20171"
down_revision: Union[str, None] = "c959e775735e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subjectorganizationlink", sa.Column("active", sa.Boolean(), nullable=True)
    )
    op.execute(
        "UPDATE public.subjectorganizationlink SET active = subject.active FROM public.subject WHERE subjectorganizationlink.subject_username = subject.username"
    )
    op.alter_column("subjectorganizationlink", "active", nullable=False)
    op.drop_column("subject", "active")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subject",
        sa.Column("active", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.execute(
        "UPDATE public.subject SET active = subjectorganizationlink.active FROM public.subjectorganizationlink WHERE subjectorganizationlink.subject_username = subject.username"
    )
    op.alter_column("subject", "active", nullable=False)
    op.drop_column("subjectorganizationlink", "active")
    # ### end Alembic commands ###
