services:
  repository:
    build:
      context: ./repository
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./repository:/repository
    tty: true
