"""Add document migration

Revision ID: 773760af9856
Revises: 81aa697cd697
Create Date: 2024-10-30 00:13:36.086648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '773760af9856'
down_revision: Union[str, None] = '81aa697cd697'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('file_handle', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('acl', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('organization_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('creator_username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('deleter_username', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('alg', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('document_handle', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['creator_username'], ['subject.username'], ),
    sa.ForeignKeyConstraint(['deleter_username'], ['subject.username'], ),
    sa.ForeignKeyConstraint(['organization_name'], ['organization.name'], ),
    sa.PrimaryKeyConstraint('document_handle')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document')
    # ### end Alembic commands ###
