"""Add active bool to subject

Revision ID: 81aa697cd697
Revises: 92f8ac5bf33f
Create Date: 2024-10-29 00:38:49.999058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '81aa697cd697'
down_revision: Union[str, None] = '92f8ac5bf33f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subject', sa.Column('active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subject', 'active')
    # ### end Alembic commands ###
