"""Rename public_key fk in n:m thing

Revision ID: c5aef9a1a909
Revises: d29028ade0cf
Create Date: 2024-10-30 19:42:56.922861

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c5aef9a1a909"
down_revision: Union[str, None] = "d29028ade0cf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subjectorganizationlink", sa.Column("public_key_id", sa.Uuid(), nullable=False)
    )
    op.drop_constraint(
        "subjectorganizationlink_public_key_fkey",
        "subjectorganizationlink",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None, "subjectorganizationlink", "publickey", ["public_key_id"], ["id"]
    )
    op.drop_column("subjectorganizationlink", "public_key")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "subjectorganizationlink",
        sa.Column("public_key", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "subjectorganizationlink", type_="foreignkey")
    op.create_foreign_key(
        "subjectorganizationlink_public_key_fkey",
        "subjectorganizationlink",
        "publickey",
        ["public_key"],
        ["id"],
    )
    op.drop_column("subjectorganizationlink", "public_key_id")
    # ### end Alembic commands ###
