"""Initial migrations

Revision ID: f711ad4100a3
Revises: 
Create Date: 2024-10-27 13:24:09.586196

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f711ad4100a3"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Organization
    op.create_table(
        "organization",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_index(
        op.f("ix_organization_name"), "organization", ["name"], unique=False
    )

    # Subject
    op.create_table(
        "subject",
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("full_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("username"),
    )
    op.create_index(op.f("ix_subject_email"), "subject", ["email"], unique=False)
    op.create_index(op.f("ix_subject_username"), "subject", ["username"], unique=False)

    # PublicKey
    op.create_table(
        "publickey",
        sa.Column("key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "subject_username", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["subject_username"],
            ["subject.username"],
        ),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_index(op.f("ix_publickey_key"), "publickey", ["key"], unique=False)

    # UserOrganizationLink (N:M)
    op.create_table(
        "userorganizationlink",
        sa.Column(
            "subject_username", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "organization_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("public_key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_name"],
            ["organization.name"],
        ),
        sa.ForeignKeyConstraint(
            ["subject_username"],
            ["subject.username"],
        ),
        sa.PrimaryKeyConstraint("subject_username", "organization_name"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("userorganizationlink")
    op.drop_index(op.f("ix_publickey_key"), table_name="publickey")
    op.drop_table("publickey")
    op.drop_index(op.f("ix_subject_username"), table_name="subject")
    op.drop_index(op.f("ix_subject_email"), table_name="subject")
    op.drop_table("subject")
    op.drop_index(op.f("ix_organization_name"), table_name="organization")
    op.drop_table("organization")
    # ### end Alembic commands ###
